services:
  mysql:
    image: mysql:8.0
    container_name: orderflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: orderflow
      MYSQL_USER: orderflow
      MYSQL_PASSWORD: orderflow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: orderflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: orderflow
      MONGO_INITDB_ROOT_PASSWORD: orderflow
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: orderflow-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: orderflow-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: orderflow-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: orderflow
      RABBITMQ_DEFAULT_PASS: orderflow
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2-alpine
    container_name: orderflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  order-service:
    build: ./order-service
    container_name: orderflow-order-service
    restart: unless-stopped
    depends_on:
      - mysql
      - kafka
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orderflow?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: orderflow
      SPRING_DATASOURCE_PASSWORD: orderflow
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: orderflow
      SPRING_RABBITMQ_PASSWORD: orderflow
      INVENTORY_SERVICE_BASE_URL: http://inventory-service:8082
    ports:
      - "8081:8081"

  inventory-service:
    build: ./inventory-service
    container_name: orderflow-inventory-service
    restart: unless-stopped
    depends_on:
      - mongodb
      - kafka
      - redis
    environment:
      SPRING_MONGODB_URI: mongodb://orderflow:orderflow@mongodb:27017/inventory?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8082:8082"

  payment-service:
    build: ./payment-service
    container_name: orderflow-payment-service
    restart: unless-stopped
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orderflow?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: orderflow
      SPRING_DATASOURCE_PASSWORD: orderflow
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PAYMENT_FAILURE_RATE: "0.2"
    ports:
      - "8083:8083"

  notification-service:
    build: ./notification-service
    container_name: orderflow-notification-service
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: orderflow
      SPRING_RABBITMQ_PASSWORD: orderflow
    ports:
      - "8084:8084"

  api-gateway:
    build: ./api-gateway
    container_name: orderflow-api-gateway
    restart: unless-stopped
    depends_on:
      - order-service
    environment:
      ORDER_SERVICE_BASE_URL: http://order-service:8081
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: orderflow-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: orderflow-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  ops-assistant:
    build: ./ops-assistant
    container_name: orderflow-ops-assistant
    restart: unless-stopped
    depends_on:
      - order-service
      - payment-service
    environment:
      ORDER_SERVICE_BASE_URL: http://order-service:8081
      PAYMENT_SERVICE_BASE_URL: http://payment-service:8083
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8085:8085"

volumes:
  mysql_data:
  mongo_data:
