spring:
  application:
    name: inventory-service

  mongodb:
    uri: mongodb://orderflow:orderflow@localhost:27017/inventory?authSource=admin

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mongodb:
      enabled: false